-- 코드를 입력하세요
SELECT B.AUTHOR_ID,	B.AUTHOR_NAME,	A.CATEGORY,SUM(C.SALES*A.PRICE) AS	TOTAL_SALES
FROM BOOK A
  JOIN AUTHOR B ON A.AUTHOR_ID =B.AUTHOR_ID
  JOIN BOOK_SALES C ON A.BOOK_ID =C.BOOK_ID 
WHERE C.SALES_DATE>='2022-01-01' AND C.SALES_DATE<'2022-02-01'
GROUP BY A.CATEGORY,A.AUTHOR_ID,B.AUTHOR_NAME
ORDER BY A.AUTHOR_ID,A.CATEGORY DESC;
