-- 코드를 입력하세요
SELECT YEAR(A.SALES_DATE) AS YEAR, MONTH(A.SALES_DATE) AS MONTH,B.GENDER,COUNT(DISTINCT A.USER_ID)	AS USERS
FROM ONLINE_SALE A
JOIN USER_INFO B
 ON B.USER_ID = A.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR(A.SALES_DATE), MONTH(A.SALES_DATE), B.GENDER
ORDER BY YEAR,MONTH,GENDER;
