SELECT CONCAT(CASE 
                    WHEN MONTH(DIFFERENTIATION_DATE) >=10 THEN 4
                    WHEN MONTH(DIFFERENTIATION_DATE) >=7 THEN 3 
                    WHEN MONTH(DIFFERENTIATION_DATE) >=4 THEN 2
                    ELSE 1
                    END
             ,'Q') AS QUARTER,
        COUNT(*) AS	ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER